site_name: FTC Community Docs
repo_url: https://github.com/Skyhawkbotics/firstdocs
repo_name: Skyhawkbotics/firstdocs
site_dirïƒ: ../site
edit_uri: edit/setup/source/docs/
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
  font:
    text: Oxanium
  palette:
    primary: orange